# .pages.yml

media:
  input: public/images
  output: /images

content:
  - name: posts
    label: 博客文章
    path: content/posts
    type: collection

    filename: '{fields.slug}.mdx'

    fields:
      - name: slug
        label: Slug
        type: text

      - name: title
        label: 标题
        type: text

      - name: description
        label: 描述
        type: text

      - name: date
        label: 日期
        type: date

      - name: tags
        label: 标签
        type: text
        list: true

      - name: pin
        label: 置顶
        type: boolean
        default: false

      - name: public
        label: 公开
        type: boolean
        default: true

      - name: cover
        label: 封面
        type: image

      - name: body
        label: 正文
        type: rich-text

actions:
  - name: content-sync
    label: Sync Content
    workflow: content-sync.yml
    ref: main
    confirm:
      title: Sure sync content?
      message: This will trigger the deployment workflow.
      button: Sync
      
  - name: deploy
    label: Deploy to Vercel
    workflow: deploy.yml
    ref: main
    confirm:
      title: Sure deploy?
      message: This will trigger the deployment workflow.
      button: Deploy

  - name: merge-content
    label: Merge Edit to Main
    workflow: merge.yml
    ref: edit
    confirm:
      title: Sure merge?
      message: This will merge edit branch to main.
      button: Merge
  